const DOTLIST_WISDOM = [
  "Small choices. Big progress.",
  "Choose lightly. Work clearly.",
  "One thing. Right now.",
  "Let the list be long. Let the next step be small.",
  "Pick the task you want to do next.",
  "A dot is not pressure. It is a quiet yes.",
  "Choose one task, then start.",
  "Do the task that feels most ready to meet you.",
  "The day gets lighter one honest choice at a time.",
  "Clarity is built by choosing, not by staring.",
  "The list can hold the noise. You only need the next note.",
  "Momentum does not need drama.",
  "A calm start is still a start.",
  "The right next thing usually arrives quietly.",
  "Work follows willingness better than force.",
  "Trust the small preference you can actually feel.",
  "Finish gently. Continue deliberately.",
  "A chain is only a path of recent yeses.",
  "Let completion be simple.",
  "The task you choose is the task that can move.",
  "Attention is easier when the room is quiet.",
  "Do less deciding while you work.",
  "The dot marks readiness, not importance.",
  "Put everything down. Pick one thing up.",
  "A small list ritual can steady a large day.",
  "The next task does not need to justify itself.",
  "When unsure, compare gently.",
  "A clear path beats a perfect plan.",
  "The list remembers so you do not have to.",
  "Start with the task that opens the door.",
  "The day is made of returns.",
  "Choose the task with the least resistance.",
  "Deep work often starts as a small preference.",
  "Let the method carry the choice.",
  "Every dot is a little less friction.",
  "Move the day forward without making it loud.",
  "Enough structure. Plenty of air.",
  "Your work can be deliberate without being severe.",
  "The next good step is enough.",
  "A calm list makes room for real focus.",
  "Do the thing that feels closest.",
  "Direction is a series of tiny selections.",
  "One selected task is better than ten anxious priorities.",
  "A quiet yes is stronger than a forced should.",
  "Make a mark. Follow the mark.",
  "The newest dot comes first.",
  "Attention likes a clean edge.",
  "The best system disappears while you work.",
  "Today only needs a next action.",
  "Choose with care. Work without second-guessing.",
  "A dot is a decision you can see.",
  "Soft discipline is still discipline.",
  "You do not need a new plan. You need the next selected task.",
  "Work becomes easier when choice is finished first.",
  "The list is allowed to be unfinished.",
  "A focused minute counts.",
  "The smallest honest step changes the shape of the day.",
  "Choose what has life in it.",
  "Let the task become obvious one comparison at a time.",
  "The chain knows where focus begins.",
  "Good work can start quietly.",
  "Progress is often a lowered voice.",
  "One dot, one breath, one action.",
  "No rush. No drift.",
  "Let the list hold everything else.",
  "The next action is not a verdict.",
  "Gather everything. Carry only one thing.",
  "Readiness is useful information.",
  "Let finished work leave cleanly.",
  "Return unfinished work without guilt.",
  "There is peace in choosing once.",
  "Make the day navigable.",
  "Work the newest dot first.",
  "The method is only here to make work feel lighter.",
  "The list becomes beautiful when it stops arguing with you.",
  "A good day is one clear return after another.",
  "Find the next yes.",
  "Selection before effort.",
  "Less force. More follow-through.",
  "Make one visible choice.",
];

export function getDailyWisdom(date = new Date()) {
  const dayKey = `${date.getFullYear()}-${date.getMonth()}-${date.getDate()}`;
  const index = Array.from(dayKey).reduce((total, char) => total + char.charCodeAt(0), 0);
  return DOTLIST_WISDOM[index % DOTLIST_WISDOM.length];
}

export function getWisdomLibrary() {
  return DOTLIST_WISDOM;
}
